collections:
  - rfta.lib.utk.edu/
  - rfta-artists.lib.utk.edu/
  - digital.lib.utk.edu/collections/islandora/object/collections:acwiley
  - digital.lib.utk.edu/collections/islandora/object/collections:ascoop
  - digital.lib.utk.edu/collections/islandora/object/gsmrc:roth
  - digital.lib.utk.edu/collections/islandora/object/collections:civilwar
  - digital.lib.utk.edu/collections/islandora/object/collections:archivision
  - digital.lib.utk.edu/collections/islandora/object/collections:bcpl
  - digital.lib.utk.edu/collections/islandora/object/collections:heilman
  - digital.lib.utk.edu/collections/islandora/object/collections:brehm
  - digital.lib.utk.edu/collections/islandora/object/collections:walden
  - digital.lib.utk.edu/collections/islandora/object/collections:dabney
  - digital.lib.utk.edu/collections/islandora/object/collections:cDanielCartoon
  - digital.lib.utk.edu/collections/islandora/object/collections:cdf
  - digital.lib.utk.edu/collections/islandora/object/collections:ekcd
  - digital.lib.utk.edu/collections/islandora/object/collections:burford
  - digital.lib.utk.edu/collections/islandora/object/collections:vanvactor
  - digital.lib.utk.edu/collections/islandora/object/collections:agee
  - digital.lib.utk.edu/collections/islandora/object/collections:boydcs
  - digital.lib.utk.edu/collections/islandora/object/collections:bass
  - digital.lib.utk.edu/collections/islandora/object/collections:druid
  - digital.lib.utk.edu/collections/islandora/object/collections:revwar
  - digital.lib.utk.edu/collections/islandora/object/collections:harp
  - digital.lib.utk.edu/collections/islandora/object/collections:insurancena
  - digital.lib.utk.edu/collections/islandora/object/gsmrc:webster
  - digital.lib.utk.edu/collections/islandora/object/collections:tenncities
  - digital.lib.utk.edu/collections/islandora/object/collections:gamble
  - digital.lib.utk.edu/collections/islandora/object/collections:kefauver
  - digital.lib.utk.edu/collections/islandora/object/gsmrc:50yrcove
  - digital.lib.utk.edu/collections/islandora/object/collections:arrowmont
  - digital.lib.utk.edu/collections/islandora/object/gsmrc:colloquy
  - digital.lib.utk.edu/collections/islandora/object/collections:calahan
  - digital.lib.utk.edu/collections/islandora/object/collections:indtruth
  - digital.lib.utk.edu/collections/islandora/object/collections:humbug
  - digital.lib.utk.edu/collections/islandora/object/collections:emancip
  - digital.lib.utk.edu/collections/islandora/object/collections:jsevier
  - digital.lib.utk.edu/collections/islandora/object/collections:knoxgardens
  - digital.lib.utk.edu/collections/islandora/object/collections:hesler
  - digital.lib.utk.edu/collections/islandora/object/collections:mugwump
  - digital.lib.utk.edu/collections/islandora/object/collections:egypt
  - digital.lib.utk.edu/collections/islandora/object/collections:scopes
  - digital.lib.utk.edu/collections/islandora/object/gsmrc:kintner
  - digital.lib.utk.edu/collections/islandora/object/gsmrc:adams
  - digital.lib.utk.edu/collections/islandora/object/collections:phoenix
  - digital.lib.utk.edu/collections/islandora/object/collections:mpabaker
  - digital.lib.utk.edu/collections/islandora/object/collections:ruskin
  - digital.lib.utk.edu/collections/islandora/object/collections:playbills
  - digital.lib.utk.edu/collections/islandora/object/gsmrc:pcard00
  - digital.lib.utk.edu/collections/islandora/object/collections:ramseyfp
  - digital.lib.utk.edu/collections/islandora/object/collections:tatum
  - digital.lib.utk.edu/collections/islandora/object/collections:rmtravis
  - digital.lib.utk.edu/collections/islandora/object/collections:sanborn
  - digital.lib.utk.edu/collections/islandora/object/collections:bakerav
  - digital.lib.utk.edu/collections/islandora/object/collections:hbs
  - digital.lib.utk.edu/collections/islandora/object/gsmrc:smhc
  - digital.lib.utk.edu/collections/islandora/object/collections:native
  - digital.lib.utk.edu/collections/islandora/object/gsmrc:rfj
  - digital.lib.utk.edu/collections/islandora/object/collections:tennessean
  - digital.lib.utk.edu/collections/islandora/object/collections:alumnus
  - digital.lib.utk.edu/collections/islandora/object/collections:tdh
  - digital.lib.utk.edu/collections/islandora/object/collections:agrtfn
  - digital.lib.utk.edu/collections/islandora/object/collections:agrtfhs
  - digital.lib.utk.edu/collections/islandora/object/collections:tenngirl
  - digital.lib.utk.edu/collections/islandora/object/collections:tndp
  - digital.lib.utk.edu/collections/islandora/object/collections:tennvolsmag
  - digital.lib.utk.edu/collections/islandora/object/gsmrc:thompson
  - digital.lib.utk.edu/collections/islandora/object/collections:torch
  - digital.lib.utk.edu/collections/islandora/object/collections:univmonthly
  - digital.lib.utk.edu/collections/islandora/object/collections:utkcomm
  - digital.lib.utk.edu/collections/islandora/object/collections:agrutesc
  - digital.lib.utk.edu/collections/islandora/object/collections:fbpro
  - digital.lib.utk.edu/collections/islandora/object/collections:womenbball
  - digital.lib.utk.edu/collections/islandora/object/collections:ladycross
  - digital.lib.utk.edu/collections/islandora/object/collections:ladygolf
  - digital.lib.utk.edu/collections/islandora/object/collections:ladyrowing
  - digital.lib.utk.edu/collections/islandora/object/collections:ladysoft
  - digital.lib.utk.edu/collections/islandora/object/collections:ladytennis
  - digital.lib.utk.edu/collections/islandora/object/collections:ladytrack
  - digital.lib.utk.edu/collections/islandora/object/collections:ladyvolley
  - digital.lib.utk.edu/collections/islandora/object/collections:marchingband
  - digital.lib.utk.edu/collections/islandora/object/collections:utrecord
  - digital.lib.utk.edu/collections/islandora/object/collections:utsmc
  - digital.lib.utk.edu/collections/islandora/object/collections:menbase
  - digital.lib.utk.edu/collections/islandora/object/collections:menbball
  - digital.lib.utk.edu/collections/islandora/object/collections:mencross
  - digital.lib.utk.edu/collections/islandora/object/collections:mengolf
  - digital.lib.utk.edu/collections/islandora/object/collections:swim
  - digital.lib.utk.edu/collections/islandora/object/collections:mentennis
  - digital.lib.utk.edu/collections/islandora/object/collections:mentrack
  - digital.lib.utk.edu/collections/islandora/object/collections:wrestling
  - digital.lib.utk.edu/collections/islandora/object/collections:univcat
  - digital.lib.utk.edu/collections/islandora/object/collections:ladysoccer
  - digital.lib.utk.edu/collections/islandora/object/collections:vpmoore
  - digital.lib.utk.edu/collections/islandora/object/collections:voice
  - digital.lib.utk.edu/collections/islandora/object/collections:voloh
  - digital.lib.utk.edu/collections/islandora/object/collections:volvoices
  - digital.lib.utk.edu/collections/islandora/object/collections:yrb
  - digital.lib.utk.edu/collections/islandora/object/collections:garner
  - digital.lib.utk.edu/collections/islandora/object/collections:wwiioh
  - digital.lib.utk.edu/collections/islandora/object/gsmrc:wderfilms
  - digital.lib.utk.edu/collections/islandora/object/gsmrc:derris
